version: "3.8"

services:
  backend:
    build:
      context: ./server
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    volumes:
      - ./server:/app
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./client
    ports:
      - "3000:80"
    depends_on:
      - backend

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
